wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1659363434
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 51
      - 53
      - 55
      2:
      - 1
      - 3
      - 5
      - 9
      - 41
      - 51
      - 53
      - 55
      4: 3.8.8
      5: 0.12.21
      8:
      - 5
