wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1659369894
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 41
      - 51
      - 53
      - 55
      3:
      - 16
      4: 3.8.8
      5: 0.12.21
      8:
      - 5
config:
  desc: null
  value:
    data_params:
      batch_size: 16
      csv:
        enabled: true
        path: ../log
      dataset_path: ../../data/timbre
      num_workers: 0
      saver:
        enabled: false
        save_dir: ../out
      spectrogram:
        mel:
          frame_size: 1024
          hop_length: 256
          segment_signal_length: 16000
          spectrogram_dims:
          - 80
          - 63
        stft:
          spectrogram_dims:
          - 80
          - 63
        type: mel
      visualizer:
        enabled: false
        save_dir: ../out
    exp_params:
      LR: 0.0001
      kld_weight: 1.0e-06
      manual_seed: 1265
      scheduler_gamma: 0.95
      weight_decay: 0.0
    log_level: 6
    logging_params:
      name: MusicVAEFlat
      save_dir: logs/
    model_params:
      conv2d_channels:
      - 128
      - 64
      - 32
      - 16
      kernel_size:
      - 3
      - 3
      latent_dim: 32
      loss:
        function: L1
      name: MusicVAEFlat
      output_padding:
      - 1
      - 0
      padding:
      - 1
      - 1
      spectrogram_dims:
      - 1
      - 80
      - 63
      stride:
      - 2
      - 1
    show_logs: true
    trainer_params:
      gpus: []
      max_epochs: 100
exp_params.LR:
  desc: null
  value: 0.007456619470855096
optimizer:
  desc: null
  value: sgd
